#MariaDB
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  mysql-password: MTIzNDU2
  mysql-root-password: YWxmcmVzY28=
  mysql-user: cm9ydGl6
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-volume
  labels:
    app: mariadb
    type: local
spec:
  storageClassName: manual
  claimRef:
    name: mariadb-pv-claim
    namespace: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    #path: "/mnt/data/alf_vol/mysql_data"
    #if macOS, create folder on volume
    path: "/Volumes/Data/Development/Volumes/alf_vol/mysql_data"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb:10.7.1
        name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-password
        - name: MYSQL_DATABASE
          value: alfresco
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - name: mariadb-persistent-storage
            mountPath: /var/lib/mysql
        resources:
          limits:
            cpu: 1500m
            memory: 1500Mi
          requests:
            cpu: 800m
            memory: 768Mi
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-pv-claim
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    app: mariadb
spec:
  selector:
    app: mariadb
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  sessionAffinity: None
  type: LoadBalancer
---
#Solr
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solr6-pv-claim
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: solr6-pv-volume
  labels:
    app: solr6
    type: local
spec:
  storageClassName: manual
  claimRef:
    name: solr6-pv-claim
    namespace: default
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    #path: "/mnt/data/alf_vol/solr_data"
    #if macOS, create folder on volume
    path: "/Volumes/Data/Development/Volumes/alf_vol/solr_data"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr6
  labels:
    app: solr6
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solr6
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: solr6
    spec:
      containers:
      - image: alfresco/alfresco-search-services:1.4.0
        imagePullPolicy: IfNotPresent
        name: alfreco-search
        envFrom:
          - configMapRef:
              name: solr6
        volumeMounts:
          - name: solr6-persistent-storage
            mountPath: /opt/alfresco-search-services/data
      volumes:
        - name: solr6-persistent-storage
          persistentVolumeClaim:
            claimName: solr6-pv-claim
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: solr6
  name: solr6-service
  namespace: default
spec:
  ports:
  - port: 8983
    protocol: TCP
    targetPort: 8983
  selector:
    app: solr6
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: solr6
  namespace: default
data:
  SOLR_ALFRESCO_HOST: "alfresco"
  SOLR_ALFRESCO_PORT: "8080"
  SOLR_SOLR_HOST: "solr6"
  SOLR_SOLR_PORT: "8983"
  SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
  #HTTP by default
  ALFRESCO_SECURE_COMMS: "none"
  SOLR_JAVA_MEM: "-Xms2g -Xmx2g"