#MariaDB
apiVersion: v1
kind: Secret
metadata:
  name: db-secret-clean-arch
type: Opaque
data:
  mysql-password: U3lzMjAyMkBQYXNz
  mysql-root-password: cm9vdA==
  mysql-user: b3J0aXpyYWY=
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-volume
  labels:
    app: mariadb
    type: local
spec:
  storageClassName: manual
  claimRef:
    name: mariadb-pv-claim
    namespace: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    #path: "/mnt/data/alf_vol/mysql_data"
    #if macOS, create folder on volume
    path: "/Volumes/Data/Development/Volumes/alf_vol/mysql_data"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb:10.7.1
        name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret-clean-arch
              key: mysql-root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret-clean-arch
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret-clean-arch
              key: mysql-password
        - name: MYSQL_DATABASE
          value: alfresco
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - name: mariadb-persistent-storage
            mountPath: /var/lib/mysql
        resources:
          limits:
            cpu: 1500m
            memory: 1500Mi
          requests:
            cpu: 800m
            memory: 768Mi
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-pv-claim
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    app: mariadb
spec:
  selector:
    app: mariadb
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  sessionAffinity: None
  type: LoadBalancer
---